language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
# Add additional versions here as appropriate.
node_js:
- "stable"
# Lint errors should trigger a failure.
before_script:
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
