language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
# Add additional versions here as appropriate.
node_js:
- "stable"
# Lint errors should trigger a failure.
script:
- npm run build
